### ISSUE TITLE
Use Mvvm cross and bind to INotifyPropertyChanged

### ISSUE THREAD

**Issue by amerkoleci** [grokys/Perspex#1]
Would be possible to bind to INotifyPropertyChanged or use libraries like Mvvm cross?
Wpf has DataContext like concept, how we can bind to external models?
Any sample?

Here is a link on how to bind to an instance of INotifyPropertyChanged:

http://social.msdn.microsoft.com/Forums/en-US/36bf6ecb-70ea-4be3-aa35-b9a9cbc9a078/observable-from-any-property-in-a-inotifypropertychanged-class?forum=rx

Thanks,

Amer

**Comment by grokys** [comment]
Closing this as I don't see any reason why it wouldn't be supported. In fact, it should be easier than in WPF as PerspexObject implements INotifyPropertyChanged.
