### ISSUE TITLE
Implement PerspexObject Clone support

### ISSUE THREAD

**Issue by amerkoleci** [grokys/Perspex#19]
Allowing cloning of PerspexObject and all its properties (values) would be usefull, specially brush clones etc.

**Comment by grokys** [comment]
This is something @SuperJMN is working on right now I believe.

However, could you give a use-case to help us understand what you need?

**Comment by amerkoleci** [comment]
Wpf has the concept of Freezable and Animatable, Brush derives from this so the user can Clone a brush and CloneCurrentValue (which clones instance and copies properties value).

**Comment by grokys** [comment]
I think it's unlikely that Perpsex will have Freezable - it's more likely we'll go with immutable objects, though that hasn't been decided for good.

However, I still don't know why you *need* cloning. Could you give a use-case?

**Comment by amerkoleci** [comment]
Wpf brush linear gradiend and radial gradient can set the mapping mode (absolute or relative), during rendering (to Direct2D) I need to remap
thoose values to bounds, thus I need to clone the brush and remap some values, I can with no problem hardcode the clone method but
was wondering if you were going to implement this.

**Comment by grokys** [comment]
Ok, thanks. Yes I need to work out how that situation will be handled. Do you see any problems with making gradient brushes mutable?

**Comment by amerkoleci** [comment]
Nope, basically I check whether the brush is relative to bounds and map start/end point in linear gradient brush, the mapping method is this:

public static Point MapPoint(Rect bounds, Pointp)
		{
			return new Point(bounds.Left + p.X * bounds.Width, bounds.Top + p.Y * bounds.Height);
		}

**Comment by SuperJMN** [comment]
Hey, just for our information, I'm working on a ITreeReplicator that takes a PerspexObject and generates a replica of it :)

**Comment by grokys** [comment]
Closing this as I don't think it makes sense and would be hard when considering that the order in which properties are set makes a difference. Please re-open if you really need it.
