### ISSUE TITLE
Tests to write

### ISSUE THREAD

**Issue by grokys** [grokys/Perspex#46]
Random list of tests to write, as I think of them while doing something else...

- [x] Make sure TabStrip/TabControl first tab is initially selected
- [x] Make sure TabStrip/TabControl tabs are selected when tabs removed

**Comment by Robertofon** [comment]
why don't you assign it to me

**Comment by grokys** [comment]
I'm currently in the process of refactoring a lot of this stuff, so there's probably not much point right now. I will let you know when the refactoring is complete.

**Comment by grokys** [comment]
Ok @Robertofon - I've given up on refactoring - if you'd still like to do it, you're welcome!

**Comment by Robertofon** [comment]
OK, I'll give a try hopefully tonight....

**Comment by grokys** [comment]
@Robertofon - if you've not already made a start on this, probably best to hold off - I'm refactoring the `ItemsControl` based controls again.

**Comment by Robertofon** [comment]
Well, summer has too many oportunities. I actually did a look at it and seems like the first half of the thest are already created and working. The removal part seems to miss.

**Comment by Robertofon** [comment]
Could not resist and created two tests. But it was worth it. Semms like TabControl's SelectedContent does not get updated. I left it for you to decide and then fix.
